import type { Metadata } from 'next';
import './globals.css';
import { GeistSans } from 'geist/font/sans';
GeistSans;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={`${GeistSans.variable}`}>
      <body className='min-h-screen font-sans antialiased grainy'>
        {children}
      </body>
    </html>
  );
}
